Repository Learn-Write-Repeat/LWR-WebApp, pull requests merged in 2021-07, with the labels that each got.

#7 added license
  README.md
Labels: DCP21, 🟪 Level0

#8 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DCP21, 🟪 Level0

#10 created react app frontend
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: DCP21, 🟩 Level1

#11 Added Node.js and express Fixes #9
  backend/.gitignore
  backend/index.js
  backend/package-lock.json
  backend/package.json
Labels: DCP21, enhancement, 🟪 Level0

#15 Added express rest api
  backend/.env.sample
  backend/index.js
  backend/models/blog.js
  backend/package-lock.json
  backend/package.json
Labels: DCP21, backend, 🟨 Level2

#17 home page
  frontend/package-lock.json
  frontend/public/Images/dev.PNG
  frontend/public/Images/profile.PNG
  frontend/src/App.js
  frontend/src/Components/Content.js
  frontend/src/Components/Footer.js
  frontend/src/Components/Header.js
  frontend/src/Components/style.css
Labels: DCP21, frontend, 🟩 Level1

#18 Connected backend with frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/public/Images/test-thumbnail.jpg
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Components/Blog/Blog.css
  frontend/src/Components/Blog/Blog.js
  frontend/src/Components/Blog/useFetch.js
  frontend/src/Components/Content.js
  frontend/src/Components/Content/Content.css
  frontend/src/Components/Content/Content.js
  frontend/src/Components/Content/head-img.jpg
  frontend/src/Components/Content/useFetch.js
  frontend/src/Components/Create/Create.css
  frontend/src/Components/Create/Create.js
  frontend/src/Components/Footer.js
  frontend/src/Components/Footer/Footer.css
  frontend/src/Components/Footer/Footer.js
  frontend/src/Components/Header.js
  frontend/src/Components/Header/Header.css
  frontend/src/Components/Header/Header.js
  frontend/src/Components/Login/Login.css
  frontend/src/Components/Login/Login.js
  frontend/src/Components/Signup/Signup.css
  frontend/src/Components/Signup/Signup.js
  frontend/src/Components/Update/Update.css
  frontend/src/Components/Update/Update.js
  frontend/src/Components/Update/useFetch.js
  frontend/src/Components/style.css
  frontend/src/index.css
Labels: DCP21, frontend, 🟧 Level3
